#! /bin/sh
#
# Copyright (C)2017-2018 inspur Inc. <http://www.inspur.com>
#    FileName: klog
#      Author: Inspur RAS Team <changxch@inspur.com>
#        Date: 2017-08-08
# Description: {start | stop | restart | status} for klog
#              


dir="/usr/sbin"

function start()
{
	if [ ! -d ${dir} ]; then
		echo "Directory ${dir} does not exist"
		exit 1
	fi
	if [ ! -f ${dir}/klogload ]; then
		echo "File ${dir}/klogload does not exist"
		exit 1
	fi

	sh ${dir}/klogload
}

function stop()
{
	if [ ! -d ${dir} ]; then
		echo "Directory ${dir} does not exist"
		exit 1
	fi
	if [ ! -f ${dir}/klogunload ]; then
		echo "File ${dir}/klogunload does not exist"
		exit 1
	fi

	sh ${dir}/klogunload	
}

function help_info()
{
	echo -e "Usage: klog [start | stop | restart | status]"
}

if [ 0 -eq $# ]; then
	help_info
	exit 1
fi
case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	status)
		status_info=$(systemctl status klog)
		echo -e ${status_info}
		;;
	*)
		echo -e "$0 $1 unknown operation"
		help_info
		exit 1
		;;
esac
